# -*- generated by 1.0.12 -*-
import da
_config_object = {}

class P(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def setup(self, name, **rest_190):
        super().setup(name=name, **rest_190)
        self._state.name = name
        pass

    def run(self):
        self.output('Hello World from:', self._state.name, ', AKA:', self._id)

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        ps = self.new(P)
        self._setup(ps, ('bob',))
        self._start(ps)
