# -*- generated by 1.0.12 -*-
import da
_config_object = {}

class P(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def setup(self, name, **rest_195):
        super().setup(name=name, **rest_195)
        self._state.name = name
        pass

    def run(self):
        self.output('Printing the process name :', self._state.name, ' and the process id ', self._id)

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        num_processes = 2
        ps = self.new(P, num=num_processes)
        self._setup(ps, ('bob',))
        self._start(ps)
