# -*- generated by 1.0.12 -*-
import da
_config_object = {}

class P(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def setup(self, processes, **rest_197):
        super().setup(processes=processes, **rest_197)
        self._state.processes = processes
        pass

    def run(self):
        for p in self._state.processes:
            self.output(self._id, ' says HELLO to process ', p)

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        num_processes = 2
        ps = self.new(P, num=num_processes)
        self._setup(ps, (ps,))
        self._start(ps)
