# -*- generated by 1.0.12 -*-
import da
_config_object = {}

class P(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def setup(self, processes, **rest_207):
        super().setup(processes=processes, **rest_207)
        self._state.processes = processes
        pass

    def run(self):
        for p in self._state.processes:
            self.send(('hello', self._id), to=p)

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        num_processes = 2
        ps = self.new(P, num=num_processes)
        for p in ps:
            self._setup(p, ((ps - {p}),))
        self._start(ps)
